apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sto-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sto-web.name" . }}
    chart: {{ include "sto-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateType }}
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{ .Values.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "sto-web.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "sto-web.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: {{ "java_opts" | upper }}
            value: "{{ .Values.config.javaOptions }}"
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: {{ include "sto-web.fullname" . }}
                key: log-level
          
         
          
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }} 
              protocol: TCP

          resources: {{ toYaml .Values.resources | indent 12 }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
