apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sto-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sto-web.name" . }}
    chart: {{ include "sto-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sql-user: {{ .Values.secrets.sqlUser | b64enc | quote }}
  sql-password: {{ .Values.secrets.sqlPassword | quote }}
  ssl-password: {{ .Values.secrets.sslPassword | b64enc | quote }}
  stoweb-user: {{ .Values.secrets.stowebUser | b64enc | quote }}
  stoweb-password: {{ .Values.secrets.stowebPassword | quote }}

